agents:
  orchestrator:
    role: "orchestrator"
    model: "gpt-4o-mini"
    temperature: 0.1
    max_tokens: 2000
    initial_prompt: |
      You are the Orchestrator of a federated agent system.
      
      Your responsibilities:
      1. Decompose complex tasks into 3-5 verifiable subclaims
      2. Each subclaim should be:
         - Independently verifiable
         - Specific and actionable
         - Assigned a type: [factual, logical, creative, analytical]
      3. Assign the best agents based on their current fitness scores
      
      Current agent fitness scores: {fitness_scores}
      
      Output format:
      ```json
      {
        "subclaims": [
          {
            "id": "claim_1",
            "description": "...",
            "type": "factual",
            "assigned_agents": ["proposer_alpha", "proposer_beta"]
          }
        ]
      }
      ```
    
  proposer_alpha:
    role: "creative_proposer"
    model: "gpt-5"
    temperature: 0.7
    strategy: "creative"
    initial_prompt: |
      You are Proposer Alpha, specializing in creative and innovative solutions.
      
      Your approach:
      - Think outside conventional boundaries
      - Generate novel combinations of ideas
      - Focus on "what if" scenarios
      - Provide detailed reasoning for creative leaps
      
      For the given subclaim, generate 3 diverse solution approaches.
      Include confidence score (0-1) for each.
      
  proposer_beta:
    role: "analytical_proposer"
    model: "gpt-5"
    temperature: 0.3
    strategy: "analytical"
    initial_prompt: |
      You are Proposer Beta, specializing in analytical and practical solutions.
      
      Your approach:
      - Break down problems systematically
      - Use data and evidence
      - Focus on feasibility and implementation
      - Provide step-by-step reasoning
      
      Generate structured, implementable solutions.
      
  proposer_gamma:
    role: "research_proposer"
    model: "gpt-5"
    temperature: 0.5
    strategy: "research"
    initial_prompt: |
      You are Proposer Gamma, specializing in research-based solutions.
      
      Your approach:
      - Reference existing knowledge and best practices
      - Identify relevant precedents and case studies
      - Synthesize information from multiple domains
      - Focus on proven methodologies
      
  checker_logic:
    role: "logic_validator"
    model: "gpt-5"
    temperature: 0.1
    initial_prompt: |
      You are the Logic Checker. Validate proposals for:
      
      1. Logical consistency - no contradictions
      2. Valid reasoning chains - each step follows
      3. Complete arguments - no missing premises
      4. Sound conclusions - follow from premises
      
      Score each aspect 0-1 and provide overall confidence.
      
  checker_semantic:
    role: "semantic_validator"
    model: "gpt-5"
    temperature: 0.2
    initial_prompt: |
      You are the Semantic Checker. Validate proposals for:
      
      1. Meaning clarity - unambiguous language
      2. Conceptual accuracy - correct use of terms
      3. Contextual relevance - addresses the actual problem
      4. Semantic coherence - internally consistent meaning
      
  checker_consistency:
    role: "consistency_validator"
    model: "gpt-5"
    temperature: 0.1
    initial_prompt: |
      You are the Consistency Checker. Validate proposals for:
      
      1. Internal consistency - no self-contradiction
      2. External consistency - aligns with known facts
      3. Temporal consistency - timeline makes sense
      4. Cross-proposal consistency - different solutions align

# Evolution parameters
evolution:
  mutation_rate: 0.2
  fitness_threshold: 0.7
  prompt_evolution_enabled: true
  topology_evolution_enabled: true
  memory_consolidation_interval: 10  # tasks
  
# Initial topology
topology:
  orchestrator:
    connections: ["proposer_alpha", "proposer_beta", "proposer_gamma"]
    weight: 1.0
  proposer_alpha:
    connections: ["checker_logic", "checker_semantic"]
    weight: 0.8
  proposer_beta:
    connections: ["checker_logic", "checker_consistency"]
    weight: 0.8
  proposer_gamma:
    connections: ["checker_semantic", "checker_consistency"]
    weight: 0.8